### ISSUE TITLE
Get error as Transport was not defined

### ISSUE THREAD

**Issue by nathancse** [Iandenh/cakephp-sendgrid#1]
Hi,

I am using Cakephp 3.x and followed as per instruction. When i tried to send an email i am getting following error.
Cannot send email, transport was not defined. Did you call transport() or define  a transport in the set profile?

Could you please update me to resolve this issue

**Comment by Iandenh** [comment]
Hi, sorry for the late response.

Did you add the config in your app.php?

```php
'Email' => [
    'Sendgrid' => [
        'transport' => 'SendgridEmail',
    ],

],
'EmailTransport' => [
    'SendgridEmail' => [
        'className' => 'SendgridEmail.Sendgrid',
        'api_key' => 'API_KEY_HERE'
    ]
]
```

If you added it as the readme you can send a email like:
```php
$email = new Email('Sendgrid');
$email->from(['me@example.com' => 'My Site'])
    ->to('you@example.com')
    ->subject('About')
    ->send('My message');
```
