### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ramdcet** [Iandenh/cakephp-sendgrid#23]
Tried But not working
  Problem 1

    - Installation request for iandenh/cakephp-sendgrid ^1.8 -> satisfiable by iandenh/cakephp-sendgrid[1.8.0, 1.8.1].
    - Can only install one of: cakephp/cakephp[4.1.1, 3.x-dev].
    - Can only install one of: cakephp/cakephp[3.x-dev, 4.1.1].
    - Can only install one of: cakephp/cakephp[3.x-dev, 4.1.1].
    - Conclusion: install cakephp/cakephp 3.x-dev
    - Installation request for cakephp/cakephp (locked at 4.1.1, required as ^4.0) -> satisfiable by cakephp/cakephp[4.1.1].

My Cakephp version is 4.1.1

**Comment by Iandenh** [comment]
Hi @Ramdcet,

You can use the 3.0.0 version of the plugin.
I just fixed an error with the latest Sendgrid SDK.
